# Generated by Django 3.0.5 on 2020-05-01 14:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('garage', models.IntegerField(default=0)),
                ('sqft', models.IntegerField()),
                ('lot_size', models.DecimalField(decimal_places=1, max_digits=5)),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('photo_main', models.ImageField(upload_to='photo/%Y/%m/%d')),
                ('photo_1', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d')),
                ('photo_2', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d')),
                ('photo_3', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d')),
                ('photo_4', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d')),
                ('photo_5', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d')),
                ('photo_6', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d')),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.Realtor')),
            ],
        ),
    ]
